source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BorderedView', :exclusive => true do
  pod "BorderedView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BorderedView", :path => "../"

  
end
